CREATE SEQUENCE DOCKER.BOARD_TABLE_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 NOMAXVALUE
 NOCYCLE
 CACHE 20
 NOORDER
 NOKEEP;


-- board_table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE board_table CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE DOCKER.BOARD_TABLE
(
    ID             NUMBER              DEFAULT "DOCKER"."BOARD_TABLE_SEQ".nextval  NOT NULL,
    BOARDTITLE     VARCHAR2(50 BYTE),
    BOARDWRITER    VARCHAR2(20 BYTE),
    BOARDPASS      VARCHAR2(20 BYTE),
    BOARDCONTENTS  VARCHAR2(500 BYTE),
    BOARDHITS      NUMBER              DEFAULT 0,
    CREATEDAT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    FILEATTACHED   NUMBER              DEFAULT 0
)
TABLESPACE USERS
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE
(
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    BUFFER_POOL DEFAULT
)
MONITORING;

ALTER TABLE DOCKER.BOARD_TABLE ADD CONSTRAINT SYS_C007678 PRIMARY KEY (ID);

-- board_file_table

CREATE SEQUENCE DOCKER.BOARD_FILE_TABLE_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 NOMAXVALUE
 NOCYCLE
 CACHE 20
 NOORDER
 NOKEEP;


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE board_file_table CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE DOCKER.BOARD_FILE_TABLE
(
    ID                NUMBER              DEFAULT "DOCKER"."BOARD_FILE_TABLE_SEQ".nextval  NOT NULL,
    ORIGINALFILENAME  VARCHAR2(100 BYTE),
    STOREDFILENAME    VARCHAR2(100 BYTE),
    BOARDID           NUMBER
)
TABLESPACE USERS
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE
(
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    BUFFER_POOL DEFAULT
)
MONITORING;

ALTER TABLE DOCKER.BOARD_FILE_TABLE ADD CONSTRAINT SYS_C007680 PRIMARY KEY (ID);

ALTER TABLE DOCKER.BOARD_FILE_TABLE ADD CONSTRAINT FK_BOARD_FILE FOREIGN KEY (BOARDID) REFERENCES "DOCKER"."BOARD_TABLE"(ID);